### ISSUE TITLE
Add support for dynamic linking in Linux

### ISSUE THREAD

**Issue by evpo** [evpo/EncryptPad#10]
Linux packages prefer dynamic linking.

**Comment by martin-langhoff** [comment]
following this to hear when it's ready :-)

**Comment by evpo** [comment]
Implemented the switch as below. It disables static linking and uses system `botan` and `zlib`.
```
configure.sh --all --use-system-libs
```
The changes are in [dinlink](https://github.com/evpo/EncryptPad/tree/dynlink) branch. I will need to test them thoroughly on other platforms before merging to `master`.

I also moved the target binaries to `./bin/release` directory. They were hard to find before.

@martin-langhoff , you can have a look if I am on the right track or wait until it's tested and merged.

**Comment by evpo** [comment]
Tested and merged to `master`. In addition to the dependencies from [#7](https://github.com/evpo/EncryptPad/issues/7) `botan` and `zlib` are required for `--use-system-libs`.

Package names are below:

Fedora:
- `botan-devel` 
  installs `zlib` automatically as dependency

Ubuntu:
- `libbotan1.10-dev`
- `zlib1g-dev`

**Comment by martin-langhoff** [comment]
Thank you! Will be preparing an rpm spec in coming days. If that works well
I'll submit it to fedora for inclusion. ~m

**Comment by martin-langhoff** [comment]
Looking good! Will be preparing rpm spec for this.

Do you think you'd make a release? These improvements are significant for Linux users :-)

**Comment by evpo** [comment]
Yes, definitely. I will make a release shortly.

**Comment by evpo** [comment]
I have implemented a better CLI interface in [nice_cli branch] (https://github.com/evpo/EncryptPad/tree/nice_cli). I will make the next release after I update all script files, test it and merge to `master`.

**Comment by evpo** [comment]
@martin-langhoff 

I have tested and merged to `master` and everything is ready for the release. I only need to build and sign binaries. I also created [CHANGES](https://github.com/evpo/EncryptPad/blob/master/CHANGES.md) to list all fixes and improvements. Do you want me to include your `gnuvim` contribution to the release or you are OK to wait for the next one?

**Comment by martin-langhoff** [comment]
Hey I'm sorry about the delay! Family life :-) Will put a PR in later today with the shellscript.

**Comment by evpo** [comment]
@martin-langhoff 

I need some family time too :) Finally I have made the release. You can find it [here](https://github.com/evpo/EncryptPad/releases/tag/v0.3.2.2).
