### ISSUE TITLE
Switch from python2 to python3

### ISSUE THREAD

**Issue by dmknght** [evpo/EncryptPad#101]
It has been a year since python2 is EOL and Debian testing removed python2 on their repository. I'm wondering if EncryptPad can switch to python3 and requirements for compiling it.

**Comment by evpo** [comment]
python3 should work with the script as it's written to support both versions. `configure.py` finds python through: `#!/usr/bin/env python` It brings python2 at the moment but if the default `python` becomes `python3`, we should be ok.

**Comment by evpo** [comment]
As far as my tests show python3 works and python2 is not required. Let me know if any issues. I am closing the issue for now.

**Comment by dmknght** [comment]
Confirm python3 works fine with the script.
