### ISSUE TITLE
Scroll window doesn't scale when font size is increased

### ISSUE THREAD

**Issue by girishnair12345** [evpo/EncryptPad#105]
Very Minor Issue

Open a file(ensure the file is large enough that scroll bars appear), 
Go to System preferences -> Change font size -> Click OK

After the new settings get applied the window size doesn't show all the contents in the bottom as the container has taken the view size based on the previous font size

**Comment by evpo** [comment]
I don't know if the bug still exists in newer versions. I could not reproduce. Open again if you think, it's still there.
