### ISSUE TITLE
Key File Generation Bug

### ISSUE THREAD

**Issue by EmadFathy** [evpo/EncryptPad#107]
A bug in key generation process.

To reproduce the bug:

- From encryption menu choose "Generate Key..." or use the toolbar icon, "Generate Key" dialog box appears.
- Choose "Key in repository", enter invalid file name (eg. demo:123) and press "OK" button.
- "Passphrase for Key File" appears, enter a password and confirmation, then press "OK" button.
- A message box appears asking you "Do you want to use the generated key for this file?", click whatever you want.
- Go to the key repository directory "encryptpad_repository" in my portable mode situation.
- You will find a zero length file, supposed to be the key with a truncated file name (according the example used here it was just "demo").

**Expected behavior:**

If the user enter an invalid file name, an error message should appear and the process of creation of the key file stops until the user enter a valid filename.

**Environment:**

Windows 10 & EncryptPad-0.5.0.1-Beta in portable-mode.

**Comment by evpo** [comment]
thanks for raising the issues.

**Comment by EmadFathy** [comment]
Any news about the coming release ?

**Comment by evpo** [comment]
fixed
