### ISSUE TITLE
icons too small - Windows display issues with hires 4k display

### ISSUE THREAD

**Issue by clach04** [evpo/EncryptPad#126]
icons are too small on 4k high DPI display screen/monitor with Windows 10

## Issue

![image](https://user-images.githubusercontent.com/424032/223023087-476b2912-4094-4d81-9730-07b64d8223e8.png)

## Workaround

Set properties to override DPI settings, in the File Explorer:

* Right-Click exe, and choose Properties
* In the Properties dialog:
    * Select the "Compatibility" tab (near the top)
    * Click the "Change High DPI Settings" button
    * Select checkbox labeled "Overide High DPI Scaling Behavior"
    * Under "Scaling Performed By:", choose "System: Enhanced"
    * Click "OK"
    * Click "Apply"

Result:

![image](https://user-images.githubusercontent.com/424032/223023193-d11ee134-9a6a-4fb3-8f5a-9b93fc9ffbc1.png)

**Comment by clach04** [comment]
Thanks for making this tool available, it is really easy to use 👍

**Comment by evpo** [comment]
Thanks for providing the workaround. I have changed the icons. The original issue should not be a problem from version 0.5.0.4

**Comment by clach04** [comment]
Thank you! Somehow I missed this update 😴 .

A very belated confirmation that https://github.com/evpo/EncryptPad/releases/tag/v0.5.0.4 build works fine with Windows 11 and  a 4K display.

**Comment by clach04** [comment]
I linked to EncryptPad in my readme for https://github.com/clach04/puren_tonbo#openpgp---gpg--pgp - I have some command line tools that are grep-like for searching encrypted text files.
