### ISSUE TITLE
Cannot open file on cifs filesystem 

### ISSUE THREAD

**Issue by cbommb** [evpo/EncryptPad#127]
I get  "Cannot open '/mnt/[some_path]/password.epd' error while opening file on cifs drive (mount option : ` cifs  auto,rw,user,noperm 0 0` .

```
encryptpad --log-severity verbose --log-file encrypt.log --lang en /mnt/[some_path]/password.epd
cat encrypt.log 
2023-03-26 10:36:26.553 INFO  [31535] [main@162] Log instance started
```

* I can open this file if I copy it on local FS.
* Outside Encryptpad everything is fine : browsing cifs filesystem, opening docs (pdf, text, etc...),...

Please let me know how to provide more detail about the error (verbose log does not seem to work as I expect). 

Context : 
* encryptpad 0.5.0.2 Beta
* os : Ubuntu 22.10

**Comment by evpo** [comment]
I know this is an old issue. Probably not relevant anymore. The logging has been improved significantly in the new version v0.5.0.3. It should now report the description of IO issue from the OS in the log.

**Comment by evpo** [comment]
Feel free to open again if you continue with the logging above.
