### ISSUE TITLE
Virus? ect.

### ISSUE THREAD

**Issue by danfarce** [evpo/EncryptPad#131]
After opening the  zip file (encryptpad0_5_0_2_win32) .Windows defender said it was clean. But trying to run 
encryptpad or encryptcli windows stopped execution. I then scanned both files with
https://www.virustotal.com/gui/home/upload
   Both scans returned with this.
2 security vendors and no sandboxes flagged this file as malicious
Reanalyze
7dc0f17a52378d5fea1bc72a13cfcf0f87f8755b47aef782f57c08b40601e3b6
EncryptPad.exe
Anybody else?

**Comment by evpo** [comment]
Thanks for the report. It happened in the past (as in this issue https://github.com/evpo/EncryptPad/issues/67 ). I submitted files to the vendors then. They investigated and added it to their database.

**Comment by evpo** [comment]
I uploaded encryptcli.exe to VirusTotal and it came back with only one vendor detecting a problem called Rising. I could not find their official web site to report a false positive. It's impossible to keep all vendors happy. I will only submit the files to large vendors who have the service of raising false positive cases. For now I am closing the ticket for there is not much I can do.
