### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by sergeevabc** [evpo/EncryptPad#132]
Windows 7 x64, EncryptPad 0.5.0.2 x86

* Download and unpack app to `C:\EncryptPad`
* Launch app and
  * Type `abc` as content
  * Click Save
  * Type `abc.epd` as filename
  * Type and confirm `abc` as password
* App is crashed as follows
  ![2023-11-15 encryptpad 01](https://github.com/evpo/EncryptPad/assets/373718/ae80eed2-35e5-4b8f-bdb5-118d127675ed)

**Comment by sergeevabc** [comment]
Err... Hello?

**Comment by evpo** [comment]
Hi, I've seen a similar problem before. What's your hardware? You can also enable logging. Run `encryptpad.exe --help` in cmd to see how.

**Comment by sergeevabc** [comment]
Intel Core 2 Duo T7250 @ 2.00 GHz, 4 GB DDR2 RAM

``` console
$ encryptpad --log-file enclog.txt --log-severity verbose
$ type enclog.txt
INFO  [19476] [qMain@162] Log instance started
INFO  [19476] [MainWindow::saveAs@585] selectedFilter:
INFO  [19476] [MainWindow::saveAs@596] selection.file_name: C:/EncryptPad/abc.epd
INFO  [19476] [MainWindow::saveAs@597] selection.filter: EncryptPad (*.epd)
```

**Comment by evpo** [comment]
Another link describes how to use the intel emulator: https://steamcommunity.com/sharedfiles/filedetails/?id=2362590754

**Comment by evpo** [comment]
As time allows, I will try to compile Botan with disabled SSE4 for users like yourself. In fact I am working on a new release and if everything goes well, I may be able to disable SSE4 requirement in the new release.

**Comment by evpo** [comment]
The new release is available: https://github.com/evpo/EncryptPad/releases/tag/v0.5.0.3

I disabled the sse4 components of the Botan library but I don't have the hardware to test handy. Let me know if it's fixed.

**Comment by sergeevabc** [comment]
I confirm that 0.5.0.3 has this issue fixed, no crash on my end.
