### ISSUE TITLE
Release file for noble?

### ISSUE THREAD

**Issue by Nebuchadnezzar94** [evpo/EncryptPad#138]
Yo I can't use the repository because  Ubunutu's latest version doesn't have a release file. Do I just use the release file for Jammy? I know that's not recommended generally, but as I understand it this lack of a release file is Ubuntu's problem and not yours. I don't know when they'll add one, and I prefer doing all my downloads from signed repositories, just easier and more secure (right now I'm using an AppImage).

**Comment by evpo** [comment]
Hi, the package for Noble was added several minutes ago. Try again and let us know please.

**Comment by Nebuchadnezzar94** [comment]
> Hi, the package for Noble was added several minutes ago. Try again and let us know please.

Hey, thanks for that! It seems to work now without any problems.
