### ISSUE TITLE
Compilation crashes on "#include <QtWidgets>"

### ISSUE THREAD

**Issue by Rich700000000000** [evpo/EncryptPad#24]
I attempted to install it, and received this error:

    fatal error: QtWidgets: No such file or directory

I don't know why I got this, I have QT5 installed. Here's the full error:

	make -f Makefile.qt_ui RELEASE=on USE_SYSTEM_LIBS=
	make[1]: Entering directory `/home/peterspc/PackageDownloads/EncryptPad-master/build'
	mkdir -p ./qt_build
	cd ./qt_build && qmake -r -spec linux-g++ "CONFIG+=release" ../../qt_ui/EncryptPad.pro
	make -C ./qt_build
	make[2]: Entering directory `/home/dave/Packages/EncryptPad-master/build/qt_build'
	g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I../../../../anaconda3/mkspecs/linux-g++ -I../../qt_ui -I../../../../anaconda3/include/QtCore -I../../../../anaconda3/include/QtGui -I../../../../anaconda3/include -I../../deps/botan/build/include -I../../deps/stlplus/portability -I../../back_end_src -I. -I. -I../../qt_ui -I. -o release/obj/application.o ../../qt_ui/application.cpp
	In file included from ../../back_end_src/packet_stream.h:29:0,
		         from ../../back_end_src/packet_composer.h:29,
		         from ../../back_end_src/encryptor.h:25,
		         from ../../qt_ui/async_load.h:26,
		         from ../../qt_ui/mainwindow.h:27,
		         from ../../qt_ui/application.h:24,
		         from ../../qt_ui/application.cpp:23:
	../../back_end_src/epad_utilities.h:114:13: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
		     return nullptr;
		     ^
	In file included from ../../qt_ui/mainwindow.h:32:0,
		         from ../../qt_ui/application.h:24,
		         from ../../qt_ui/application.cpp:23:
	../../qt_ui/load_save_handler.h:21:21: fatal error: QtWidgets: No such file or directory
	 #include <QtWidgets>
		             ^
	compilation terminated.
	make[2]: *** [release/obj/application.o] Error 1
	make[2]: Leaving directory `/home/peterspc/PackageDownloads/EncryptPad-master/build/qt_build'
	make[1]: *** [x_make] Error 2
	make[1]: Leaving directory `/home/peterspc/PackageDownloads/EncryptPad-master/build'
	make: *** [all] Error 2

**Comment by evpo** [comment]
Below is what we install on the CI Ubuntu server.

    sudo apt-get install qt53tools

You can also have a look at [the yaml](https://github.com/evpo/EncryptPad/blob/master/.travis.yml) for other needed packages. The build log is (here)[https://travis-ci.org/evpo/EncryptPad].

**Comment by evpo** [comment]
You can also look at which Qt version it uses. This error usually occurs when Qt4 is used. Maybe your `$PATH` variable leads to Qt4 qmake instead of Qt5. Look at the output from `which qmake` and see where it is or if it's a simbolic link if it is from version 5.

**Comment by Rich700000000000** [comment]
I ran that and got:

    /home/peterspc/anaconda3/bin/qmake

**Comment by evpo** [comment]
Use `qmake --version` to learn which qt version you use. If you installed qt5, find where it is.  Use `find / -name qmake -type f` to find other versions you installed.

**Comment by Rich700000000000** [comment]
I ran: `qmake --version` and got:

    QMake version 2.01a
    Using Qt version 4.8.7 in /home/dave/anaconda3/lib

I ran `find / -name qmake -type f` and got:

    /opt/Qt/5.7/android_x86/bin/qmake
    /opt/Qt/5.7/gcc_64/bin/qmake
    /opt/Qt/5.7/android_armv7/bin/qmake

**Comment by evpo** [comment]
If you run the command below before you build, it should use the new qmake because it will be earlier in the path resolution.

    export PATH=/opt/Qt/5.7/gcc_64/bin/:$PATH

**Comment by Rich700000000000** [comment]
Hey, that woked! Awesome!

And now it's giving me a different error:

	In file included from ../../qt_ui/set_key_dialog.cpp:22:0:
	./ui_set_key_dialog.h:13:25: fatal error: QtGui/QAction: No such file or directory
	 #include <QtGui/QAction>
		                 ^
	compilation terminated.
	make[2]: *** [release/obj/set_key_dialog.o] Error 1
	make[2]: Leaving directory `/home/dave/Packages/EncryptPad-master/build/qt_build'
	make[1]: *** [x_make] Error 2
	make[1]: Leaving directory `/home/dave/Packages/EncryptPad-master/build'
	make: *** [all] Error 2


This is going to become a cat-and-mouse game, isn't it?

**Comment by evpo** [comment]
Yes, it is probably going to take some back and forth steps. Which Linux distro you are using? I will test compilation on Qt 5.7 and see if it works. In the meantime, you could try building with 5.3 (`qt53tools` package). CI build uses 5.3.

**Comment by evpo** [comment]
By the way, did you clean temporary files after building it with Qt4. If not, delete `encryptpad/build/qt_buid` directory.

**Comment by Rich700000000000** [comment]
Ubuntu 14.04 LTS

**Comment by evpo** [comment]
By the way, there is [a compiled binary](http://evpo.net/encryptpad/#install-on-ubuntu) available for Ubuntu. You can install it, unless you determined to build from the source. I am happy to help you with the build anyway.

**Comment by Rich700000000000** [comment]
Huh. 

I was going to do that, but my sources list is already screwed up majorly, I didn't want to make it worse.

**Comment by evpo** [comment]
OK, so the next step for you is to clean build directories as I said above. You will also need to clean with `configure.sh --clean`

**Comment by Rich700000000000** [comment]
Understood. Hey, I'll try that and get back to you.

**Comment by evpo** [comment]
I am closing the issue as it is a problem in the build environment. Nevertheless, we can continue our conversation here. I will help you as I can.
