### ISSUE TITLE
Change the frequency of password prompts?

### ISSUE THREAD

**Issue by mkrier** [evpo/EncryptPad#40]
I guess this isn't an "Issue", it's just annoying-  every once in a while it will prompt me for password again when I save.  (And I mean when I just leave the file open, I don't mean opening it again).  Can I change the frequency of how often it does that?  For example--- zero. In other words, only when I freshly open the file after closing it?  I can't find that in the settings...

**Comment by evpo** [comment]
For stronger security, EncryptPad never keeps plain text passphrases in memory. When you enter your passphrase, it generates keys with an S2K algorithm and saves a number of them for future use. Every time you save your file, it uses one of those keys. Currently there are five keys. I will make it configurable in the future. In the meantime, you can change the constant (see the link below). If you make the number reasonably high, it will never ask you for the passphrase again.

Link: (key_service.h:45)[https://github.com/evpo/EncryptPad/blob/master/back_end_src/key_service.h#L45]

**Comment by evpo** [comment]
I am closing this issue. The proposed are captured in #41

**Comment by mkrier** [comment]
You're saying I have to recompile it?

**Comment by mkrier** [comment]
Well... compile it at all?  I've never compiled it, I just installed the windows exe.

**Comment by evpo** [comment]
You have two options: recompile it or wait for the next release where #41 will be done and everybody will be able to reconfigure it without compiling anything.
