### ISSUE TITLE
Fail to open file using command line argument when the path contains non-ascii characters

### ISSUE THREAD

**Issue by TJYSunset** [evpo/EncryptPad#44]
Environment: Windows 10 with Anniversary Update
EncryptPad Version: 0.3.2.3 Beta

---

Well I don't know whether it is true that it doesn't support all the non-ascii characters, but at least it doesn't support CJK characters. This also effects those who set encryptpad as the file types' default program.
For example:
`encryptpad C:\example.gpg` worked fine, but `encryptpad C:\中文\example.gpg` will give a message box saying "Cannot open the file because it does not exist".
The `open` command in GUI menu worked fine.

**Comment by evpo** [comment]
Thanks for reporting. It needs to be fixed it in the next release.
