### ISSUE TITLE
is it ok to use both gpg and encryptpad on the same file?

### ISSUE THREAD

**Issue by Bulmer** [evpo/EncryptPad#54]
Why I ask is that I was encrypting/decrypting the same file with both gpg, on the commandline and encryptpad and somehow the file became permanently unreadable (even without encryption, passphrase or key).  Its ok, as I do have another copy, but i'm just puzzled as to how it happened. Gpg and encryptpad would be 100% compatible wouldn't they? I compiled EncryptPad from source.

**Comment by evpo** [comment]
They should be compatible. There are tests in `func_tests` that encrypt with gpg and decrypt with encryptpad and vice versa. There was an issue before 0.3.2.3 in which EncryptPad used text flag and binary files were decrypted in text mode and stripped CR. See #21. However, it was fixed long time ago. Did you use the source files after 0.3.2.3 for compilation?

**Comment by Bulmer** [comment]
Yes, I used the 0.3.2.3 source for compilation. I just tried run_all_tests.sh (in func_tests) and when asked for the passphrase I used the one in passphrase.txt. If that is the correct passphrase to use, it failed.

**Comment by evpo** [comment]
It should not ask for a passphrase but read the passphrases from a file descriptor. The tests are run as below:

  ./configure.sh --run-func-tests --debug

Look at [the Travis build](https://travis-ci.org/evpo/EncryptPad#L931) to see what the normal output should be.
This file gives the sequence of commands before the tests are run on Travis: [link](https://github.com/evpo/EncryptPad/blob/master/.travis.yml)

**Comment by evpo** [comment]
I think the tests don't run because of `--no-use-agent` option being obsolete with gpg2. Does your `gpg` point to `gpg2`?

**Comment by Bulmer** [comment]
> Does your gpg point to gpg2?
Yes, gpg2 --version and gpg --version give the same result.
I am using GPG 2.1.16.

> Look at the Travis build to see what the normal output should be.
Mine returns this
`./configure.sh --run-func-tests --debug
15+0 records in
15+0 records out
15728640 bytes (16 MB, 15 MiB) copied, 0.092033 s, 171 MB/s
Passphrase only
./epd_encryption_test.sh: line 27: ../bin/debug/encryptcli: No such file or directory`
Would this have anything to do my compiling without dynamic linking? The only version of encryptcli I have is in ../bin/release/encryptcli. There isn't a ../bin/debug/

**Comment by evpo** [comment]
Parameters in gpg2 are slightly different. `--no-use-agent` needs to be replaced with `--batch` in all sh files. You can replace it or I can make a patch for you quickly.

**Comment by Bulmer** [comment]
I don't have a good C ide. But I am happy to run whatever you come up with and report back a bit later.

**Comment by evpo** [comment]
Here is a link to Gist - [link](https://gist.github.com/evpo/95deafcedbc0c81de004dce353d7d2e9)

**Comment by evpo** [comment]
If you could apply this patch and run the tests again, they will run with gpg2. I have run them just now and they passed.

**Comment by evpo** [comment]
Regarding the missing `encryptcli`, you didn't build the debug version. It's not a problem. You can run

    ./configure.sh --run-func-tests

This runs in release mode and uses the `./bin/release/encryptcli`. If you want to run in debug mode, you need to compile first with `./configure.sh --all --debug --use-system-libs`

**Comment by Bulmer** [comment]
Ok, I applied the patch and now the function tests complete successfully. So, in regards to my original question, is there a possibility of any incompatibility with gpg2 in the 0.3.2.3 source?

**Comment by evpo** [comment]
By design they must be compatible as long as the encryption is symmetric and the parameters are within the range listed in [Features](http://evpo.net/encryptpad/#features). I also test the compatibility and haven't seen any issues so far since 0.3.2.3. Encrypted files are hashed and the hash is tested on decryption by both gpg and EncryptPad. If there is a problem, you should never end up with a corrupt file. Instead, the integrity check must fail first.

**Comment by Bulmer** [comment]
ok, thanks for that.
