### ISSUE TITLE
Tabs aren't always 8 characters?

### ISSUE THREAD

**Issue by JamesCC** [evpo/EncryptPad#61]
I see that tabs aren't 8 characters wide (it varies depending on the font size).

In connection - it would be great if the following options could be also added (seen in most text editors):
1. user selectable tab sizing (in terms on number of characters)
2. insert spaces rather than tabs

**Comment by evpo** [comment]
https://github.com/evpo/EncryptPad/commit/b5870d1a3411fc7c98525e62e77d65fe8b5d5e5b

**Comment by evpo** [comment]
Fixed in [0.4.0.0](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.0)
