### ISSUE TITLE
[PENDING] Unify CLI and GUI defaults

### ISSUE THREAD

**Issue by sergeevabc** [evpo/EncryptPad#68]
EncryptPad 0.3.2.5 

```encryptpad.exe``` uses ZLIB for compression by default.
```encryptcli.exe``` uses ZIP, however ZLIB is expected.

Could you be so kind to unify it to save the user from having to specify an additional CLI parameter?

**Comment by evpo** [comment]
Thanks for letting me know. I will look at it.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by evpo** [comment]
Yep, I know. Hopefully this Christmas.

**Comment by evpo** [comment]
Fixed in version [0.4.0.0](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.0)

**Comment by sergeevabc** [comment]
It works as expected now, thank you.

What about Meltdown’s threat? [Keepass][1] and [Veracrypt][2] threads indicate there are solutions. 

[1]: https://sourceforge.net/p/keepass/discussion/329220/thread/4ae796cf/
[2]: https://sourceforge.net/p/veracrypt/discussion/general/thread/824c6e66/

**Comment by evpo** [comment]
At this point I can only mention one strategy EncryptPad uses to minimize the attack surface:

https://evpo.net/encryptpad/#passphrases-in-memory
