### ISSUE TITLE
I couldn't use this symbol-> '   Spanish graphic accent

### ISSUE THREAD

**Issue by forest-hermit** [evpo/EncryptPad#69]
I could paste it but not write it with my keyboard.

**Comment by evpo** [comment]
Thanks for letting me know. What's your environment? Operating System?

**Comment by forest-hermit** [comment]
Kubuntu 17.04
Kde Plasma: 5.9.4
Kernel: 4.10.0-24
64 bits

Thanks to you for reply and your work

**Comment by evpo** [comment]
I will look at it as time allows. I have seen a blog post about a similar issue. I will try to find it first.

**Comment by forest-hermit** [comment]
Great thanks!

**Comment by evpo** [comment]
[This](http://abyssluke.hatenablog.com/entry/2017/03/20/185832) is the article in Japanese. I used my browser to translate it to English and read. However, now I see that it's probably not related to your problem because there was Ubuntu 14.04 and Qt5.2.

**Comment by forest-hermit** [comment]
Oh..

**Comment by evpo** [comment]
@forest-hermit there is a new development [release](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.0) based on Qt 5.10.0. You can download the AppImage and see if this issue is still present.

**Comment by forest-hermit** [comment]
> @forest-hermit there is a new development release based on Qt 5.10.0. You can download the AppImage and see if this issue is still present.
It seems solved +1:

**Comment by evpo** [comment]
Excellent. Thanks for a quick response

**Comment by forest-hermit** [comment]
> Excellent. Thanks for a quick response

You are welcome :) thanks for your job!
Could I use this version on a daily basis or should I wait for the stable release?

**Comment by evpo** [comment]
I have a set of automated tests and I have tested basic functionality. It appears stable. There are only two known issues at the moment: #72 and #73. I am using 0.4.0.0 myself.

However, officially this is still a development release. There will be more testing going forward. I would recommend to wait for a while. I would also appreciate any testing / feedback / opinion help.

**Comment by forest-hermit** [comment]
> I have a set of automated tests and I have tested basic functionality. It appears stable. There are only two known issues at the moment: #72 and #73. I am using 0.4.0.0 myself.

However, officially this is still a development release. There will be more testing going forward. I would recommend to wait for a while. I would also appreciate any testing / feedback / opinion help.

Ok, I will wait them and if I have time this weekend I will do some tests.

**Comment by forest-hermit** [comment]
Now I am using 4.0.2 (my first 4.x version) all perfect!
