### ISSUE TITLE
Build AppImage on Ubuntu Trusty 14.04 beause it is still supported

### ISSUE THREAD

**Issue by evpo** [evpo/EncryptPad#75]
See #71 for more details

**Comment by evpo** [comment]
Add gpg signature for the AppImage file

**Comment by evpo** [comment]
@probonopd, I've updated the AppImage and added a signature. Could you please restart your build?

**Comment by probonopd** [comment]
Restarted: https://travis-ci.org/AppImage/appimage.github.io/builds/340610862

Thanks.

**Comment by evpo** [comment]
When I run it on a clean Trusty, it fails with:

`./encryptpad0_4_0_2.AppImage: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by evpo** [comment]
The app runs fine after installing:

`sudo apt install libgl1-mesa-glx`

**Comment by evpo** [comment]
@probonopd, should it be part of AppImage?

    linuxdeployqt ./AppDir/encryptpad -bundle-non-qt-libs
    appimagetool ./AppDir encryptpad.AppImage

the above commands didn't include libGL.so.1 by default. I will investigate more when I have access to my build environment.

**Comment by evpo** [comment]
The build environment already contains `libgl1-mesa-glx`, which is pulled as a dependency to `libgl1-mesa-dev`. libGL.so.1 is not the problem. @probonopd, what's the technology that identifies if there is a window?

**Comment by evpo** [comment]
I progressed a bit further. encryptpad works fine in the real screen environment and segfaults under:

    Xvfb :99 -screen 0 800x600x24 &

when I run it as below:

    DISPLAY=:99 ./encryptpad0_4_0_2.AppImage &

**Comment by evpo** [comment]
Next step

I built EncryptPad on this machine and ran under Xvfb:
```
ubuntu@demo-trusty:~/EncryptPad$ DISPLAY=:99 ./bin/release/encryptpad &
[2] 15677
ubuntu@demo-trusty:~/EncryptPad$
ubuntu@demo-trusty:~/EncryptPad$ jobs
[1]-  Running                 Xvfb :99 -screen 0 800x600x24 &  (wd: ~)
[2]+  Running                 DISPLAY=:99 ./bin/release/encryptpad &
ubuntu@demo-trusty:~/EncryptPad$ DISPLAY=:99 xwininfo -tree -root

xwininfo: Window id: 0x169 (the root window) "EncryptPad"

  Root window id: 0x169 (the root window) "EncryptPad"
  Parent window id: 0x0 (none)
     4 children:
     0x200006 "untitled.epd": ("encryptpad" "EncryptPad")  685x453+891+396  +891+396
     0x200005 (has no name): ()  3x3+0+0  +0+0
     0x200004 (has no name): ()  1x1+0+0  +0+0
     0x200002 (has no name): ()  1x1+0+0  +0+0
```
It works.

**Comment by evpo** [comment]
I installed Xvfb on trusty on which I built Qt 5.10 and tried to run a few example Qt applications such as calculator and tetris. I got the same:

```
ubuntu@trusty-for-appimage:~/qt-everywhere-src-5.10.0/qtbase/examples/widgets/widgets/tetrix$ DISPLAY=:99 ./tetrix &
[1] 5926
ubuntu@trusty-for-appimage:~/qt-everywhere-src-5.10.0/qtbase/examples/widgets/widgets/tetrix$ QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ubuntu'

[1]+  Segmentation fault      (core dumped) DISPLAY=:99 ./tetrix
```
It seems there is a general problem with Qt 5.10 interacting with Xvfb on Trusty. At the same time those applications work with the normal X server.

**Comment by probonopd** [comment]
> It seems there is a general problem with Qt 5.10 interacting with Xvfb on Trusty. At the same time those applications work with the normal X server.

Interesting. Thanks for letting me know.
