### ISSUE TITLE
How to open/save GPG encrypted files with key-with-passphrase

### ISSUE THREAD

**Issue by martin-langhoff** [evpo/EncryptPad#8]
I would like to use this fine editor to open/save files encrypted with GPG, using my own gpg key. In other words, the equivalent of the following workflow (though naturally bypassing creating unencrypted files on disk...). Is it possible? How?

```
# saving a new file
vi new-file.txt
# gpg2 asks for passphrase, or uses in-memory passphrase from gpg-agent
gpg2 --encrypt -r martin.langhoff@gmail.com < new-file.txt > new-file.txt.gpg
rm new-file.txt

# opening existing file
# gpg2 asks for passphrase, or uses in-memory passphrase from gpg-agent
gpg2 < new-file.txt.gpg > new-file.txt
vi new-file.txt
```

**Comment by evpo** [comment]
Hi Martin,

You are using your private key and use asymmetrical encryption. It is a bit different from what EncryptPad does, as its main purpose is symmetrical encryption (only private key to encrypt and decrypt). For asymmetrical encryption I would recommend to use [GPG4USB](www.gpg4usb.org). I haven't used it myself though.

Asymmetrical keys will not work with EncryptPad. EncryptPad generates random symmetric key and then encrypts it before saving on the disk. Encrypted symmetric key is also in OpenPGP format. So you can decrypt it and open without EncryptPad. See [this tutorial](http://evpo.net/encryptpad/tutorials/open_plain_text_protect_with_key_file/key_file_protection.aspx) , especially the second half about EncryptPad key file.

Unfortunately, I don't have an agent yet. So every time you access something, you need to enter the password.

Please let me know if it makes sense. I will answer your other questions shortly. I can also write a script to imitate what you did above with encryptpad if you want.

**Comment by martin-langhoff** [comment]
Thanks for your explanation. My attempt to use asymmetrical encryption in a symmetrical fashion is because I want to ensure I am using the same key (and passphrase) for several files. This prevents the scenario of accidentally providing a wrong/different password for one of the files, and losing access to its contents.

Can EncryptPad share the (random) key across a group of files? If so, it'll work for my use case just fine. Thanks!

**Comment by evpo** [comment]
Yes, it can. The key file has one to many relationship to encrypted files. I also need to mention that I am finishing (testing phase) input / output redirection and pipes as in your scripts. The changes are in [stdin_stdout branch](https://github.com/evpo/EncryptPad/tree/stdin_stdout). It should work already and has been tested on Linux. However, I will need to test it on different operating systems before merging to master.

**Comment by martin-langhoff** [comment]
Thanks for the info, reading the tutorial is very enlightening. 

For interop purposes, I looked for ways to encrypt/decrypt compatible files with `gpg2`. Realizing that EncryptPad "keys" are actually just encrypted passphrases, I can decrypt to `STDOUT` with

```
gpg2 --decrypt ~/.encryptpad/foo.key | gpg2 --passphrase-fd 0 --batch --decrypt  /tmp/test2.gpg
```

**Comment by martin-langhoff** [comment]
To encrypt an existing file:
```
# creates /tmp/test3.txt.gpg
gpg2 --decrypt ~/.encryptpad/foo.key | gpg2 --passphrase-fd 0  --batch -c --cipher-algo AES256  /tmp/test3.txt 
# decrypt
gpg2 --decrypt ~/.encryptpad/foo.key | gpg2 --passphrase-fd 0 --batch --decrypt  /tmp/test3.txt.gpg
```

**Comment by martin-langhoff** [comment]
To complete this, I have created a shellscript that wraps vim or other commandline editor, and reads/writes files compatible with EncryptPad. This is so that the team I am working on is not locked into EncryptPad and can, for example, use it on computers without a GUI (headless, remote, etc).

See https://github.com/martin-langhoff/ml_utils/blob/master/gpgvim -- it's my grab-bag-of-scripts repo.

@evpo feel free to take gpgvim and include it with EncryptPad (changing it as you see fit) if you think it'd be of use. I think it can help people understand better what EncryptPad is doing and have an alternative tool should EP be unavailable or broken.

**Comment by martin-langhoff** [comment]
Snippet to create compatible key

```
pwmake 1024 | gpg2 -c --armor --cipher-algo AES256 > some.key
```

**Comment by martin-langhoff** [comment]
Thanks for your help, feel free to close this ticket.

**Comment by evpo** [comment]
Thank you for your example bash commands. They are very useful for interop purposes and also explain what EncryptPad key is. I will also look at your `gpgvim` and see how I can use it. I am a devoted vim user as well.

**Comment by evpo** [comment]
I have examined your `gpgvim` script. It is perfect when working with symmetric keys saved in files. [gnupg.vim](http://www.vim.org/scripts/script.php?script_id=3645) does not cover this scenario and it only works with passphrases entered in a dialogue.

**Comment by martin-langhoff** [comment]
Great to hear. From a trust, transparency, portability and compatibility PoV it might be good to offer it as part of the EncryptPad project. It can work as "documentation" for folks familiar with gpg usage.

It's small/trivial enough that I wouldn't want to maintain it as a self-standing project; but I'll be happy to maintain it / co-maintain it as part of EP. If you are interested of course.

**Comment by evpo** [comment]
Yes, I am interested. I can include it in the source tree and add to the documentation.

I saw the comment in your script regarding `TMPDIR` and vipe's ability to clean after itself. In addition to what you said, it would be good to mention vim's own temporary file to list all possible "left overs" of unencrypted data that can remain on the disk even after being deleted. `gnupg.vim` claims to exclude temporary files.

Alternatively, we can add to the documentation that there may be pieces of unencrypted data on the disk. It is acceptable in some scenarios, especially if the script is used for education.

By the way, I am adding the `gpg` commands you wrote here to `README`.

**Comment by martin-langhoff** [comment]
Great, I'll be happy to maintain it (sending you PRs, reviewing incoming PRs that affect it) in this repository.

Re `TMPDIR`; my findings are as follows:

`vi` has options that limit the number of tmpfiles created; we can set them for the default editor (my initial stab didn't work but I think it's doable). I can address it setting the default EDITOR.

This helps a bit but doesn't change the fundamentals however; `vipe` works by creating a tmpdir with a tmpfile inside; vi (and most other editors) will default to creating tmpfiles in the same dir. If the editor is killed, `vipe` cleans up the whole directory. If `vipe` (or its parent process) is killed, there's no cleanup. If there's no cleanup, one file or two makes little difference.

So the resulting fact is: regardless of editor (or `vi` settings), if the process group is killed we may leave tempfiles with secrets behind; that's how `vipe` works because that's how editors work :-/

Modern Linux has tmpdir on a ramdisk; OS X has a per-user ramdisk tmpdir; both ameliorate the problem.

**Comment by evpo** [comment]
I called `mount` on my [Open SUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed) and this is the result below.

```
> mount | grep /tmp
/dev/sda2 on /tmp type btrfs (rw,relatime,space_cache,subvolid=262,subvol=/tmp)
/dev/sda2 on /var/tmp type btrfs (rw,relatime,space_cache,subvolid=274,subvol=/var/tmp)
```
`sda2` is my hdd and not `tmpfs`.

`vipe` writes the secret data on the disk and deletes it without running `shred`. It seems that the secret bytes will remain on the HDD. I also checked `stdio.h` and `p_TMPDIR` is `/tmp`.

It's all fine with me as long as the user is warned in the documentation. I have [Known Weaknesses](http://evpo.net/encryptpad/#known-weaknesses) for the case when a piece of RAM under EncryptPad can end up in a swap file if it is not disabled. We can write something similar about your script.

**Comment by martin-langhoff** [comment]
Good point. Also old Linuxes. There will be always cases warranting a warning.

One interesting improvement would be to use /dev/shm where available. If present (linux kernels from the last decade, normal config), it's a ramdisk. Systems with `systemd` get /dev/shm contents deleted on logout which serves our purposes.

```
if [ -d /dev/shm ]; then
    export TMPDIR=/dev/shm
fi
```

**Comment by martin-langhoff** [comment]
Updated at https://github.com/martin-langhoff/ml_utils/blob/master/gpgvim

**Comment by evpo** [comment]
I will make a subdirectory similar to [zlib contribs](https://github.com/evpo/EncryptPad/tree/master/deps/zlib/contrib) and we'll add your script there.

**Comment by martin-langhoff** [comment]
Sounds good to me :-)

**Comment by evpo** [comment]
@martin-langhoff ,

I have made [the contrib subirectory](https://github.com/evpo/EncryptPad/tree/master/contrib). You can update the `README.md` file with contacts and a description. Your source will go to a subdirectory under `contrib`. Name it as you feel right.

**Comment by martin-langhoff** [comment]
PR #13 open for you. I forgot to make a subdir, as it's a single file, I hope that's ok :-)

**Comment by vatterspun** [comment]
Earlier in this thread, it appears you answered the question I was going to ask (can I open files secured with EncryptPad with other GPG decryption tools?):

> Asymmetrical keys will not work with EncryptPad. EncryptPad generates random symmetric key and then encrypts it before saving on the disk. Encrypted symmetric key is also in OpenPGP format. So you can decrypt it and open without EncryptPad. See this tutorial , especially the second half about EncryptPad key file.

The link that was in there (http://evpo.net/encryptpad/tutorials/open_plain_text_protect_with_key_file/key_file_protection.aspx) appears to be broken.

Do you know where that went?

Thanks

**Comment by vatterspun** [comment]
> Here it is https://evpo.net/encryptpad/static/en/tutorials/open_plain_text_protect_with_key_file/key_file_protection.htm

A well-written doc.  Thanks.
