### ISSUE TITLE
Add compilation dependency: zlib

### ISSUE THREAD

**Issue by fresheneesz** [evpo/EncryptPad#80]
I tried compiling this on a debian based OS and needed to install zlib. Would make sense to me to add zlib to the list of dependencies in this sentence: "All you need is to install Qt, Python and run:..."

**Comment by fresheneesz** [comment]
Actually I noticed that it does actually mention this for ubuntu. Probably wanna move that info up to the top so the steps are in chronological order..

**Comment by evpo** [comment]
Yes, we can improve the manual. Thanks.

**Comment by evpo** [comment]
Accurate build instructions for Debian and openSUSE have been added:

https://github.com/evpo/EncryptPad#build-on-debian

**Comment by fresheneesz** [comment]
Thanks!
