### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [evpo/EncryptPad#81]
Currently (as of version [0.4.0.2 Beta](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.2)) [EncryptPad](https://www.evpo.net/encryptpad/) saves configuration file (**encryptpad.ini**) in user profile folder:

`C:\Users\User\_encryptpad\encryptpad.ini`

I need a way to save configuration file in program folder (where is the executable- **encryptpad.exe**). There may be different possible solutions:

- command-line argument- for example `encryptpad.exe -portable` forces **EncryptPad** to save settings in program folder;
- on program start **EncryptPad** checks program folder for configuration file (**encryptpad.ini**) and if available, it loads settings from it;
- `portable` flag in program folder forces portable mode (configuration file saved in program folder);

Any of these options would be fine for me if I can keep program and configuration together (true portable mode- nothing is written outside program folder).

**Comment by evpo** [comment]
There is also an example of portability requirements at this link: https://www.portablefreeware.com/faq.php#seven

**Comment by smaragdus** [comment]
@evpo 

I forgot to mention one more possible way of triggering portable mode:

- a specific sub-folder in program folder, for example `data`, forces the program to save configuration file inside it;

The good about this option is that data and settings, being isolated in a single sub-folder, are easy to back-up and program update is not problematic. A couple of examples of programs which initiate portable mode that way- [ghostwriter](https://github.com/wereturtle/ghostwriter) (see Portable Mode) and [Vacuum-IM](https://github.com/Vacuum-IM/vacuum-im) (see Portable Version).

I prefer portable programs for several reasons:
- portable programs are easy to back-up;
- one can easily transfer portable programs with all their data and settings from one machine to another (no need to export registry keys, to dig into AppData which is usually a junk-yard);
- portable programs (usually) do not leave any traces and junk behind;
- with portable programs one can use different versions with different settings (even the same version with different settings)- this is very handy with testing and bug-hunting;

Having in mind the nature of the program for me full portability will be a must (at least on Windows).

You [referred](https://www.portablefreeware.com/faq.php#seven) to [The Portable Freeware](https://www.portablefreeware.com/)- actually your program has already been reviewed [there](https://www.portablefreeware.com/forums/viewtopic.php?f=2&t=24235)- it was in my review list but someone else posted about it, So if you decide to add an option to run [EncryptPad](https://www.evpo.net/encryptpad/) in portable mode most likely it will be submitted to the database- I have already added a somewhat similar program (but not cross-platform like **EncryptPad**)- [Crypto Notepad](https://github.com/Sigmanor/Crypto-Notepad), to [The Portable Freeware database](https://www.portablefreeware.com/?id=2873) so if **EncryptPad** supports portable mode I will gladly add it to the database myself- I have several reasons to prefer **EncryptPad** to other similar programs- cross-platform, light, written in  C++, no dependencies (Java, .NET, Electron), etc.

**Comment by mva1985** [comment]
I myself like to use portable apps and think it would add greatly to EncryptPad

**Comment by evpo** [comment]
There have been some progress on this issue. We published a development release. See the links below:

1. [Instructions](https://github.com/evpo/EncryptPad#portable-mode)
2. [Development release](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.3)

**Comment by evpo** [comment]
Public release with this feature has been published:

https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.4

I am closing the issue.

**Comment by smaragdus** [comment]
@evpo 

Thank you for adding an option to run **EncryptPad** in portable mode, I tested version [0.4.0.4](https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.4) and it works as expected. I [notified](https://www.portablefreeware.com/forums/viewtopic.php?f=2&t=24235#p91675) The Portable Freeware community about the portable mode.
