### ISSUE TITLE
When opening encrypted file, the app keeps prompting for a password

### ISSUE THREAD

**Issue by dmgk** [evpo/EncryptPad#82]
Got this bug report from EncryptPad port user on FreeBSD:

> Steps to reproduce.
> 
> Run encryptpad.
> Type some text.
> Save to a file with a password.
> Exit program.
> 
> Re-run encryptpad.
> Open the file you just saved.
> Enter password.
> Program keeps prompting for password.
> Fails to open the document just saved.
> 

The issue is reproducible on master and v0.4.0.4 on FreeBSD 11.2 amd64 and Arch amd64, encryptpad was built with `--use-system-libs`.

**Comment by evpo** [comment]
Can you please let me know the version of the Botan library installed there?

**Comment by dmgk** [comment]
2.9.0 on both FreeBSD and Arch.

**Comment by evpo** [comment]
My investigation led to an issue in Botan 2.9.0. I reported it and made a patch. Hopefully it will be merged in the next release. For now there are two options. Use Botan 2.8.0 or apply the patch I am attaching to this comment.

```
diff --git a/src/lib/pbkdf/pgp_s2k/pgp_s2k.cpp b/src/lib/pbkdf/pgp_s2k/pgp_s2k.cpp
index d04fb47b3..8bcf9239f 100644
--- a/src/lib/pbkdf/pgp_s2k/pgp_s2k.cpp
+++ b/src/lib/pbkdf/pgp_s2k/pgp_s2k.cpp
@@ -61,7 +61,7 @@ uint8_t RFC4880_encode_count(size_t desired_iterations)
    if(desired_iterations >= OPENPGP_S2K_ITERS[255])
       return 255;
 
-   auto i = std::upper_bound(OPENPGP_S2K_ITERS, OPENPGP_S2K_ITERS + 256, desired_iterations);
+   auto i = std::lower_bound(OPENPGP_S2K_ITERS, OPENPGP_S2K_ITERS + 256, desired_iterations);
 
    return static_cast<uint8_t>(i - OPENPGP_S2K_ITERS);
    }
```

**Comment by evpo** [comment]
Note that the patch is for https://www.freshports.org/security/botan2

Option 3: remove `--use-system-libs` when building EncryptPad

**Comment by dmgk** [comment]
Thanks for the investigation and patch, Evgeny. Can you please refer me to the your botan2 bug report? I'll raise an issue with botan2 port so it could be patched in the port tree until the issue fixed upstream.

**Comment by evpo** [comment]
Thanks to you for raising it. This bug can cause people to lose access to their data: 

Here is the link: https://github.com/randombit/botan/issues/1853

**Comment by dmgk** [comment]
Thanks!
