### ISSUE TITLE
Not an Issue but Feature Request

### ISSUE THREAD

**Issue by mva1985** [evpo/EncryptPad#84]
This might be a tall order.  But might be nice to be able to save a file as a self extracting exe file in the case of wanting to send it to another that didn't have EncryptPad

Just a thought, other then that EncryptPad is awesome

**Comment by evpo** [comment]
Thanks for the feedback and the suggestion.

I think the security conscious community frowns upon running received executables. You never know what it's going to do to your system. EncryptPad is signed by a GPG signature and distributed from Github but it's not feasible to sign and verify each executable encryption result.

There is also multi-platform support requirement. If you encrypt a file on macOS, you should be able to decrypt it on Windows and so on. It would be too difficult to create an executable for all supported platforms and it would too heavy.

Unfortunately, it cannot be done so I am closing the issue.
