### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Unixware** [evpo/EncryptPad#85]
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
----------
libX11-xcb is installed already BTW

**Comment by evpo** [comment]
what's the distribution name and version?

**Comment by Unixware** [comment]
sorry, its fedora 30 (x64)

**Comment by evpo** [comment]
Please do the following steps in bash:

1. extract the appimage files to a directory:
    ./encryptpad0_4_0_4.AppImage --appimage-extract
This will create `squashfs-root` directory
2. rename libfreetype.so.6 file to something else
    cd squashfs-root
    mv lib/libfreetype.so.6 lib/disable.libfreetype.so.6
3. start encryptpad
    ./encryptpad

Let me know if there are issues

**Comment by Unixware** [comment]
excellent! works like a charm! Looks like conflict of the built-in lib with the one at the system?

**Comment by evpo** [comment]
Yes, here is a link with more details: https://forums.gentoo.org/viewtopic-p-8198000.html?sid=ab27c1ca8e1927691858595185e18284

    symbol lookup error: /usr/lib64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
