### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by Misko2468** [evpo/EncryptPad#91]
I've done the installation and don't see the icon in my menu, or is their a command on kali? I may have installed wrong.

**Comment by evpo** [comment]
How did you install it? Did you compile it yourself?

**Comment by Misko2468** [comment]
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
sudo apt install encryptpad encryptcli

I'm new to this stuff so I probably did something wrong, or didnt do it all.

**Comment by evpo** [comment]
The package is for Ubuntu family. EncryptPad has installation script which works in multiple systems. It copies a number of files according to this structure:

    https://github.com/evpo/EncryptPad/tree/master/linux_deployment/de_install

Then it executes the following commands:

    update-icon-caches /usr/share/icons/hicolor
    update-mime-database /usr/share/mime
    update-desktop-database /usr/share/applications

It's all done under sudo

**Comment by Misko2468** [comment]
Thanks, for the info, learning is power. However I'm still new to this and I'm still not sure what to do, I think I know what to do I just don't want risk doing it wrong. Sorry for the inconvenience of a newby.

**Comment by evpo** [comment]
Sure. There is also AppImage option.
Download from here: https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.4
Manual: https://appimage.org/
Scroll down to "How to run an AppImage?"

**Comment by Misko2468** [comment]
Thanks for the assistance!
