### ISSUE TITLE
Can't install on Linux Mint 19

### ISSUE THREAD

**Issue by gbizzotto** [evpo/EncryptPad#92]
I tried the packages as instructed:
```
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
sudo apt install encryptpad encryptcli
```
It lead to
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package encryptpad
E: Unable to locate package encryptcli
```
I tried compiling the source. I cloned the repo at the latest commit and did:
```
sudo apt-get install qtbase5-dev qt5-default gcc g++ make python zlib1g-dev pkg-config
./configure.py --build-botan --build-zlib
make
```
I got 
```
botan_all.cpp:9355:10: fatal error: bzip2/bzlib.h: No such file or directory
 #include <bzlib.h>
```
I tried:
- adding the `bzip2` folder name in the include
- adding the `deps/bzip2` folder name in the include
- sudo apt-get install libz-dev (it was already there)

**Comment by evpo** [comment]
I added instructions for Ubuntu yesterday:

https://github.com/evpo/EncryptPad#ubuntu

Try them please. There is a small difference in the parameters of the configure.py script

**Comment by gbizzotto** [comment]
I see, no need to build `botan`. It worked, thx.
