### ISSUE TITLE
Any chance this editor becomes a richtext editor with basic WYSIWYG text styling? 

### ISSUE THREAD

**Issue by vasamaximov** [evpo/EncryptPad#93]
Hi all!

First: thank you all for the great piece of software!
Just curious though: are there plans to implement rich-text editing functionality? Under the hood, it still could be a text file with wiki markup, but having the WYSIWYG text tools like font face/size, predefined H1-H3/normal text styles, maybe?

Thanks again!

**Comment by evpo** [comment]
Appreciate the feedback. We have a related issue: #42 . That will be the approach to add the rich text view.
