### ISSUE TITLE
EncryptPad crashed and my file got erased

### ISSUE THREAD

**Issue by Kevin-Prichard** [evpo/EncryptPad#94]
> MacOS Catalina 10.15.5 (19F101)
> EncryptPad 0.4.0.4 Beta

This has happened twice now, once eight months ago when first we tried this app, and just now.

Both times, the encrypted file was set to zero length, deleting many changes from the edit session. The original file was backed by EncryptPad, but still, this is bad behavior. Seems as though the file was opened for write just as it died. Some safeguard is needed.

One message in the logfile-
`Aug 22 16:49:01 my_computer_name com.apple.xpc.launchd[1] (www.evpo.net/encryptpad.9588[5742]): Service exited due to SIGABRT`

I otherwise really like EncryptPad. I typically back up these encrypted files once a day, which leaves me vulnerable. That's a problem, but a separate matter from this bug.

**Is there a way to enable verbose logging, so that when this bug occurs again, I can provide more useful info?**

**Comment by evpo** [comment]
Sorry to hear that. I added an issue #95 to enable logging. The existing logging can only be enabled when building from source. I would also recommend to move to version 0.5.0.0. A few bugs related to stability have been fixed there. However, there were no known issues as you describe. It would be useful to know if the behavior manifests when encrypting from command line or it's related to GUI.

**Comment by Kevin-Prichard** [comment]
@evpo I use the prebuilt version from your site. I'll upgrade to 0.5.0.0 on my machines and will update if the bug recurs. Thanks for your efforts on this project, it's a helpful app.

**Comment by Kevin-Prichard** [comment]
This continues to occur, now in 0.5.0.0 Beta on macOS 11.2.2 Big Sur. I continue to combat it with a triggered file backup, but that sometimes isn't recent enough, and I lose data.

In the coming weeks I'll make a local build with logging around the open-write-close of that file, so I can at least understand where it actually crashes, and hopefully that will lead to a fix and PR.

**Comment by evpo** [comment]
Logging is available now in 0.5.0.1: [instructions](https://github.com/evpo/EncryptPad#command-line-encryptpad)

**Comment by evpo** [comment]
There is a new build now. If you see this problem again in v 0.5.0.1 , we can reopen the issue.
