### ISSUE TITLE
New application icon

### ISSUE THREAD

**Issue by jmico** [evpo/EncryptPad#96]
I've made a new application icon for EncryptPad, combining thewse two icons:

https://github.com/paomedia/small-n-flat/blob/master/svg/lock.svg by Arnaud Chesne
Licensed as ![CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](http://creativecommons.org/publicdomain/zero/1.0/)

https://gitlab.gnome.org/GNOME/gedit/-/blob/master/data/icons/org.gnome.gedit.svg by GNOME Design Team
File metadata states license as ![Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/), gedit project is licensed as GNU General Public License v2.0

If you are interested I can make a pull request changing all required versions (different sizes, depths, the iconset, etc).

Cheers

![EncryptPad_demo](https://user-images.githubusercontent.com/84746/97449262-3f790900-1910-11eb-8a27-527ca34f1c48.png)

**Comment by evpo** [comment]
Hi @jmico ,

These icons look great. I would be happy to replace the current lock. Please create the pull request.

Appreciate your help.

Cheers,
Evgeny

**Comment by evpo** [comment]
added to the new release 0.5.0.1
