### ISSUE TITLE
Opening search dialog by using 'CTRL-F' doesn't focus on the find text field.

### ISSUE THREAD

**Issue by cfgnunes** [evpo/EncryptPad#98]
When I press `CTRL-F` to open the _Find dialog_, the focus remains on the text and not on the search field.

Sometimes, this issue is a bit annoying if you're using only the keyboard because you always need to click on the search text field to enter the search word.

This problem does not occur when I open the search dialog by using the mouse, clicking on "Edit... -> Find...".

**Comment by cfgnunes** [comment]
I'm using EncryptPad 0.5.0.0 Beta on Ubuntu 20.04.

**Comment by evpo** [comment]
Thanks, I have seen this bug on Windows. It needs to be fixed. In the meantime you can try to press Tab after CTRL-F to avoid using the mouse.

**Comment by cfgnunes** [comment]
Hi! I've fixed this bug.

Please, accept the pull request #103  

Thanks! 💙
